# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1cba73b32289e5b9486b1bcbaf3faddc"
name = "app-name"
handle = "app-name-70"
application_url = "https://gear-colleague-snow-naturals.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "development-experiments.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://gear-colleague-snow-naturals.trycloudflare.com/auth/callback",
  "https://gear-colleague-snow-naturals.trycloudflare.com/auth/shopify/callback",
  "https://gear-colleague-snow-naturals.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
